title: Suu Nhuy
author: 
  name: giahuy
  email: giahuy2201@outlook.com
description: >-
  Curiosity takes me places
baseurl: "" # subpath
url: "https://www.suunhuy.com"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-toc
  - jekyll-seo
  
remote_theme: jekyll/minima

minima:
  skin: auto

sass:
  quiet_deps: true

toc:
  max_level: 1 # default: 6